package com.plugtree.dm.entities;

public enum LeaveType {
	ANNUAL, EDUCATION, EMERGENCY, EXAM, EXCEPTIONAL, MARRIAGE, NATIONAL_DAY, COMPANY_DAY, MATERNITY, PATERNITY, SICK, TRANSFER, UNPAID, COMPASIONATE;
}
