package com.plugtree.dm.dmdemo;

public enum LeaveType {
	ANNUAL, COMPASSIONATE, EDUCATION, EID_ALFETER, EMERGENCY,
	EXAM, EXCEPTIONAL, HAJJ, MARRIAGE, NATIONAL_DAY, PATERNITY,
	PATIENTS_ACCOMPANY, SICK, SPORTS, TRANSFER, UNPAID;
}
