package com.plugtree.dm;

import com.plugtree.dm.proj.Requirement;

rule "Completed status"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == true, compileError == null, deployError == null, testingDone == true, bugsFound.size() == 0)
    then
        req.setStatus(Requirement.Status.COMPLETED);
end

rule "Bugs found"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == true, compileError == null, deployError == null, testingDone == true, bugsFound.size() > 0)
    then
        req.setDevelopmentDone(false);
        req.setStatus(Requirement.Status.BUGS_FOUND);
end

rule "Testing not done"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == true, compileError == null, deployError == null, testingDone == false)
    then
        req.setStatus(Requirement.Status.IN_TEST);
end

rule "Deploy errors"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == true, compileError == null, deployError != null)
    then
        req.setDevelopmentDone(false);
        req.setStatus(Requirement.Status.DEPLOY_ERROR);
end

rule "Compile errors"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == true, compileError != null)
    then
        req.setDevelopmentDone(false);
        req.setStatus(Requirement.Status.COMPILE_ERROR);
end

rule "Development not done but no bugs yet"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == false, bugsFound.size() == 0, bugsFixed.size() == 0)
    then
        req.setStatus(Requirement.Status.IN_DEVELOPMENT);
end

rule "Development not done but all bugs fixed"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == false, bugsFixed.size() > 0, bugsFixed.size() == 0)
    then
        req.setStatus(Requirement.Status.BUGS_FIXED);
end

rule "Development not done after bugs"
ruleflow-group "determine-requirement-status"
lock-on-active
    when
        req: Requirement(developmentDone == false, bugsFound.size() > 0)
    then
        req.setStatus(Requirement.Status.BUGS_FOUND);
end
